### ISSUE TITLE
OAuth Button doesn't show up

### ISSUE THREAD

**Issue by mantsch** [thathoff/kirby-oauth#16]
I just installed the plugin (Kirby 3.5.3 / no other plugins) and the OAuth buttons didn't show up.

On the plugins index.js:8 starting with `if (url.indexOf(window.panel.url) === 0) { ... }` the `url.indexOf(window.panel.url)` gives me back 5, so when i change that, the OAuth button shows up.
Just read on PR #12 that there is a similar problem, so maybe this helps for debugging.

Thanks for the plugin!

Edit:
Getting different results depending on the port?
"http://localhost:3000/panel/login" -> 5
"http://localhost:8000/panel/login" -> 0

**Comment by thathoff** [comment]
Thank you. This should be fixed with v1.2.0
