### ISSUE TITLE
Kirby 3.6.0 Compatibility

### ISSUE THREAD

**Issue by thathoff** [thathoff/kirby-oauth#21]
The plugin breaks with Kirby 3.6. because of the reworked components.

**Comment by thathoff** [comment]
You can try the `dev-kirby-3.6` version in composer to use the Kirby 3.6.0 compatible version. Will release v2.0.0 when Kirby 3.6.0 get’s released.

**Comment by pReya** [comment]
> You can try the `dev-kirby-3.6` version in composer to use the Kirby 3.6.0 compatible version. Will release v2.0.0 when Kirby 3.6.0 get’s released.

Any news on a v2 release?

**Comment by thathoff** [comment]
Yeah, I’m not quite happy with the implementation of adding the buttons to the InstallScreen. But I think i’ll release this version in den next couple of days.

**Comment by pReya** [comment]
> adding the buttons to the InstallScreen

Can you describe what you mean exactly? Maybe I can help?!

**Comment by thathoff** [comment]
Sure! I’m currently replacing the whole install view to accomplish what has been possible with just a hook into the Vue Router in Kirby 3.5.

https://github.com/thathoff/kirby-oauth/pull/22/commits/23aa423d61663b68ff1da29de749d0170a1fac2c#diff-bf96165ee9d4ae3af24b75acdf7ab350b0d07b7fca6f375ef52246a6bc9c694c
vs.
https://github.com/thathoff/kirby-oauth/blob/master/src/index.js#L13

The goal is to make it possible to login with OAuth even if the panel has not created any users yet. I did not find a simple solution like the router hook in Kirby 3.5 yet.
