### ISSUE TITLE
How to use this plugin for frontend / non panel logins

### ISSUE THREAD

**Issue by kiahreading** [thathoff/kirby-oauth#31]
Hello, 

First off, thanks a lot for making this plug-in. 

I have a question about its use in the front-end. How would implement the plug-in via the front-end? Eg, what would be the bare minimum that needs to be included in a `login.php` file for example? Is each client a link to be verified?

Thanks again.

**Comment by thathoff** [comment]
Currently the plugin handles Kirby user logins. So it hooks into the Panel login view to display the login buttons and authenticates the Kirby user. So maybe you can build this with the [visitors without panel access](https://getkirby.com/docs/guide/users/permissions#visitors-without-panel-access) and the [home option for the user blueprint](https://getkirby.com/docs/reference/panel/blueprints/user#home-option).

If you want to keep completely separate users in the frontend I think the easiest option is to just use the [Oauth2-Client library](https://github.com/thephpleague/oauth2-client) this plugin uses.
