### ISSUE TITLE
Incompatibility with Kirby 4.2.0

### ISSUE THREAD

**Issue by pReya** [thathoff/kirby-oauth#37]
The latest Kirby version 4.2.0 seems to have changed some things about the Login form. With the `kirby-oauth` plugin installed, you will only see the Oauth login. Kirbys native/default form inputs, are always hidden – no matter the `onlyOauth` setting.

**Comment by thathoff** [comment]
I can reproduce this. I’ll release an update in the next couple of days.

**Comment by georgobermayrsaf** [comment]
> I can reproduce this. I’ll release an update in the next couple of days.

Hi @thathoff , do you have an update about the next release?

**Comment by thathoff** [comment]
Hi, just published v3.1.0 containing the fix! :) Thanks for your patience…
