### ISSUE TITLE
Unable to Log In to Kirby Panel After Successful Okta Authentication

### ISSUE THREAD

**Issue by stananiev** [thathoff/kirby-oauth#41]
Hi, first of all, thank you for this plugin! : )

I’d like to have the option to log in using Okta and to create new users if they don’t already exist. After completing the Okta login, I am redirected back to Kirby's login screen, but I'm not logged into the panel. There’s an `oauthError`, but the response is `{"msg": null}`, with no additional information. The redirect URI in my Okta app and the `redirectUri` are the same (`http://localhost:8888/panel/login`).

After the Okta redirection, the URL includes `code` and `state` parameters (e.g., `http://localhost:8888/panel/login?code=xxxxxxxxxxxx&state=xxxxxxxxxxxxx`).

Here’s my configuration:

```php
return [
    'thathoff' => [
        'oauth' => [
            'providers' => [
                'okta' => [
                    'class' => "Foxworth42\OAuth2\Client\Provider\Okta",
                    'issuer' => $_ENV['OKTA_ISSUER_URI'],
                    'clientId' => $_ENV['OKTA_CLIENT_ID'],
                    'clientSecret' => $_ENV['OKTA_CLIENT_SECRET'],
                    'redirectUri' => 'http://localhost:8888/panel/login',
                    'icon' => 'check',
                ],
            ],
            'onlyExistingUsers' => false,
            'defaultRole' => 'viewer',
            'allowEveryone' => true,
            'domainWhitelist' => [],
            'emailWhitelist' => [],
            'onlyOauth' => false,
        ],
    ],
];
```

**Environment:**
- `Kirby Version: 4.3.0`

**Plugins:**
- `thathoff/kirby-oauth: ^3.1`
- `foxworth42/oauth2-okta: ^1.0`

If you have any suggestions on where to look for the issue or if you need any additional information or logs, please let me know. Thank you in advance!

**Comment by thathoff** [comment]
Ahh, I think the problem is the missing provider id in the redirect URL as mentioned [here in the README](https://github.com/thathoff/kirby-oauth?tab=readme-ov-file#redirect-url). So please change your redirect URL to `http://localhost:8888/panel/login/octa`. Hopefully that fixes it!

**Comment by stananiev** [comment]
Thanks for the suggestion! I had the feeling it was something I missed ... sorry for the trouble. I tried `http://localhost:8888/panel/login/okta`, like you suggested, but it didn’t work for me.

However, using `http://localhost:8888/oauth/login/okta` did the job, and everything’s working fine now! Thanks again for your help, I’ll mark this "issue" as solved.

Cheers
