### ISSUE TITLE
Reimplement hackish button in Login screen with new custom login screen plugin type

### ISSUE THREAD

**Issue by thathoff** [thathoff/kirby-oauth#5]
[Kirby 3.2](https://github.com/getkirby/kirby/releases/tag/3.2.0-rc.1) will add a custom login screen plugin type so we might rebuild the hackish solution for adding the Login-Button into the login screen.

This might also close #2.

**Comment by bnomei** [comment]
https://getkirby.com/docs/reference/plugins/extensions/panel-login
