### ISSUE TITLE
Bug: redirectUri auto value doesn't work

### ISSUE THREAD

**Issue by LeBenLeBen** [thathoff/kirby-oauth#7]
I configured the plugin like this:

```php
c::set('blankogmbh.oauth', [
  'providers' => [
    'google' => [
      'class' => 'League\OAuth2\Client\Provider\Google',
      'clientId' => $googleClientId,
      'clientSecret' => $googleSecret
    ],
  ],
  'onlyExistingUsers' => true,
  'defaultRole' => 'blogger',
  'domainWhitelist' => ['domain.ch']
]);
```

When trying to authenticate with Google, I always got an error saying `redirect_uri_mismatch` while my redirect URL was correctly white listed in the Google Developers Console.

After investigating a bit, I found that in `src/ProvidersManager.php` line 22 to 24 the redirectUri is automatically set to `$kirby->request()->url()` when not defined; which for me results in `http://domain.io/oauth`.

Setting the redirectUri manually in the provider settings to `http://liip.io/oauth/login/google` fixes the issue.

I guess `$kirby->request()->url()` is not appropriate and should be completed with `/login/{provider-name}`, or am I missing something?

Kirby 3.2.3
kirby-oauth 1.0.0
league/oauth2-google 3.0.1

**Comment by thathoff** [comment]
Just had a look into this. `$kirby->request()->url()` should return the full current url. So when this code is called on the login route (/oauth/login/google) this returns `https://example.com/oauth/login/google`. Maybe the problem is related to another issue?
